"""empty message

Revision ID: 106017c9b74c
Revises: be3fab33e3ca
Create Date: 2020-05-21 20:57:08.702519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '106017c9b74c'
down_revision = 'be3fab33e3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('project_name', table_name='project')
    op.drop_column('project', 'project_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=80), nullable=True))
    op.create_index('project_name', 'project', ['project_name'], unique=True)
    # ### end Alembic commands ###
