"""empty message

Revision ID: 224479ab6d9f
Revises: a382eded05e2
Create Date: 2020-07-25 22:21:20.879711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224479ab6d9f'
down_revision = 'a382eded05e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_members')
    # ### end Alembic commands ###
