"""empty message

Revision ID: 311919875121
Revises: f55d1b74e94a
Create Date: 2020-03-20 18:05:39.985578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '311919875121'
down_revision = 'f55d1b74e94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(collation='utf8_unicode_ci', length=16), nullable=True))
    # ### end Alembic commands ###
