"""empty message

Revision ID: 34752ba7d925
Revises: c3e4b493b421
Create Date: 2020-03-31 21:50:01.325244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34752ba7d925'
down_revision = 'c3e4b493b421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
