"""empty message

Revision ID: 38bdad54d7ba
Revises: 1fb57d2fcb35
Create Date: 2020-04-10 15:18:15.998925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38bdad54d7ba'
down_revision = '1fb57d2fcb35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'project_id')
    # ### end Alembic commands ###
