"""empty message

Revision ID: 40c287bc706d
Revises: 529ad4cb7e27
Create Date: 2020-04-22 11:18:27.821801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40c287bc706d'
down_revision = '529ad4cb7e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('project_name', table_name='project')
    op.drop_column('project', 'project_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True))
    op.create_index('project_name', 'project', ['project_name'], unique=True)
    # ### end Alembic commands ###
