"""empty message

Revision ID: 493910a0b9de
Revises: 5192fe6a5259
Create Date: 2020-05-14 17:45:29.394416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493910a0b9de'
down_revision = '5192fe6a5259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('logo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'logo')
    # ### end Alembic commands ###
