"""empty message

Revision ID: 4d23e18963b0
Revises: f3e2818765de
Create Date: 2020-08-07 13:06:45.200373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d23e18963b0'
down_revision = 'f3e2818765de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_tags',
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='project_tags_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='project_tags_ibfk_2'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
