"""empty message

Revision ID: 5192fe6a5259
Revises: 69eb18a0653b
Create Date: 2020-05-14 17:44:39.822970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5192fe6a5259'
down_revision = '69eb18a0653b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('avatar', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True))
    # ### end Alembic commands ###
