"""empty message

Revision ID: 529ad4cb7e27
Revises: 38bdad54d7ba
Create Date: 2020-04-10 18:17:55.688547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '529ad4cb7e27'
down_revision = '38bdad54d7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'user', ['admin_id'], ['id'])
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'project', ['project_id'], ['id'])
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'admin_id')
    # ### end Alembic commands ###
