"""empty message

Revision ID: 573de6246162
Revises: 311919875121
Create Date: 2020-03-20 18:05:53.562894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573de6246162'
down_revision = '311919875121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
