"""empty message

Revision ID: 9b0e6d8dc778
Revises: 493910a0b9de
Create Date: 2020-05-21 20:43:10.312500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b0e6d8dc778'
down_revision = '493910a0b9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('project_name', table_name='project')
    op.drop_column('project', 'project_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=80), nullable=True))
    op.create_index('project_name', 'project', ['project_name'], unique=True)
    # ### end Alembic commands ###
