"""empty message

Revision ID: be3fab33e3ca
Revises: 9b0e6d8dc778
Create Date: 2020-05-21 20:48:58.216604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3fab33e3ca'
down_revision = '9b0e6d8dc778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('project_name', table_name='project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('project_name', 'project', ['project_name'], unique=True)
    # ### end Alembic commands ###
