"""empty message

Revision ID: c3e4b493b421
Revises: 573de6246162
Create Date: 2020-03-31 21:49:40.628142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3e4b493b421'
down_revision = '573de6246162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', mysql.VARCHAR(collation='utf8_unicode_ci', length=500), nullable=True))
    # ### end Alembic commands ###
