"""empty message

Revision ID: c8e970ef62ca
Revises: 85fe3f6c3b3f
Create Date: 2020-07-21 20:50:42.037651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e970ef62ca'
down_revision = '85fe3f6c3b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_user_request', sa.Column('positive_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_user_request', 'positive_status')
    # ### end Alembic commands ###
