"""empty message

Revision ID: f5aef320e306
Revises: 40c287bc706d
Create Date: 2020-04-22 11:19:23.350435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5aef320e306'
down_revision = '40c287bc706d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_name', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'project', ['project_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'project_name')
    # ### end Alembic commands ###
