"""empty message

Revision ID: f5f2034721ca
Revises: 106017c9b74c
Create Date: 2020-05-21 20:57:33.782978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f2034721ca'
down_revision = '106017c9b74c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'project_name')
    # ### end Alembic commands ###
